# services/llama-explanation/monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "llama_rules.yml"

scrape_configs:
  - job_name: 'llama-explanation'
    static_configs:
      - targets: ['llama-explanation:9090']
    scrape_interval: 10s
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
