global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'market-intelligence'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Core Infrastructure
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # API Gateway & Load Balancer
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Multi-Agent Services
  - job_name: 'agent-orchestration'
    static_configs:
      - targets: ['agent-orchestration:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'finbert-sentiment'
    static_configs:
      - targets: ['sentiment-analysis:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'gpt4-strategy'
    static_configs:
      - targets: ['gpt4-strategy:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'llama-explanation'
    static_configs:
      - targets: ['llama-explanation:8004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'tft-forecasting'
    static_configs:
      - targets: ['tft-forecasting:8005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Trading & Risk Services
  - job_name: 'virtual-trading'
    static_configs:
      - targets: ['virtual-trading:8006']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'options-strategy'
    static_configs:
      - targets: ['options-strategy-engine:8007']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'brokerage-integration'
    static_configs:
      - targets: ['brokerage-integration:8008']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Data Pipeline
  - job_name: 'data-ingestion'
    static_configs:
      - targets: ['data-ingestion:8009']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'realtime-processing'
    static_configs:
      - targets: ['realtime-processing:8010']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Database Monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
