global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@marketintelligence.com'
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 2h
    - match:
        alertname: HighAPIUsageCosts
      receiver: 'cost-alerts'
      repeat_interval: 15m

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://webhook-receiver:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'devops@marketintelligence.com'
        subject: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Summary: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
    slack_configs:
      - channel: '#alerts-critical'
        color: 'danger'
        title: '🚨 Critical Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Service:* {{ .CommonLabels.service }}
          *Summary:* {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}

  - name: 'warning-alerts'
    slack_configs:
      - channel: '#alerts-warning'
        color: 'warning'
        title: '⚠️ Warning Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Service:* {{ .CommonLabels.service }}

  - name: 'cost-alerts'
    slack_configs:
      - channel: '#alerts-cost'
        color: '#ff9900'
        title: '💰 Cost Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Details:* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
