# Security Scanning Configuration (.github/workflows/security.yml)
name: Security Scans

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:

jobs:
  container-security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - finbert-agent
          - llama-agent
          - gpt4-agent
          - tft-agent
          - orchestrator-agent
          - fastapi-gateway
          - react-dashboard
    
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest'
        format: 'sarif'
        output: 'trivy-${{ matrix.image }}.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-${{ matrix.image }}.sarif'

  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'MIP Platform'
        path: '.'
        format: 'ALL'
    
    - name: Upload Dependency Check results
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: reports/
